export const movieData = [
    {
        id: Math.random(),
        title: "Avengers: Endgame",
        description: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
        posterURL: "https://cdn.europosters.eu/image/1300/posters/avengers-endgame-journey-s-end-i122136.jpg",
        rating: 5,
    },
      {
        id: Math.random(),
        title: "Jumanji: The Next Level",
        description: "In Jumanji: The Next Level, the gang is back but the game has changed. As they return to rescue one of their own, the players will have to brave parts unknown from arid deserts to snowy mountains, to escape the world's most dangerous game.",
        posterURL: "https://i2.wp.com/posterspy.com/wp-content/uploads/2019/12/7c2c1d70014089.5de9728c1d7a0.png",
        rating: 3,
    },
    {
        id: Math.random(),
        title: "Shutter Island",
        description: "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
        posterURL: "https://m.media-amazon.com/images/M/MV5BZjIwNjljZTUtODYzZC00YWRkLThiNjAtZjg1ZTRlMDRiNDhmXkEyXkFqcGdeQXVyMTEyODk3NTgz._V1_FMjpg_UY720_.jpgg",
        rating: 4,
    },
    {
        id: Math.random(),
        title: "Boss Baby",
        description: "A suit-wearing, briefcase-carrying baby pairs up with his 7-year old brother to stop the dastardly plot of the CEO of Puppy Co.",
        posterURL: "https://teaser-trailer.com/wp-content/uploads/THE-BOSS-BABY-2-FAMILY-BUSINESS-movie-poster.jpg",
        rating: 3,
    },
    {
        id: Math.random(),
        title: "Garfield",
        description: "Jon Arbuckle buys a second pet, a dog named Odie. However, Odie is then abducted and it is up to Jon's cat, Garfield, to find and rescue the canine.",
        posterURL: "https://m.media-amazon.com/images/M/MV5BMjU4MzU1MjM0MV5BMl5BanBnXkFtZTYwMTQxODc3._V1_FMjpg_UY705_.jpg",
        rating: 2,
    },
    {
        id: Math.random(),
        title: "Jurassic Park",
        description: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
        posterURL: "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_FMjpg_UX667_.jpg",
        rating: 4,
    },
    {
        id: Math.random(),
        title: "Home Alone",
        description: "An eight-year-old troublemaker must protect his house from a pair of burglars when he is accidentally left home alone by his family during Christmas vacation.",
        posterURL: "https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UY720_.jpg",
        rating: 3,
    },
    {
        id: Math.random(),
        title: "Batman v Superman",
        description: "Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs.",
        posterURL: "https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UY720_.jpg",
        rating: 3,
    },
    {
        id: Math.random(),
        title: "The Shawshank Redemption",
        description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        posterURL: "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX674_.jpg",
        rating: 5,
    },
    {
        id: Math.random(),
        title: "Slumdog Millionaire",
        description: "A Mumbai teenager reflects on his life after being accused of cheating on the Indian version of 'Who Wants to be a Millionaire?'.",
        posterURL: "https://m.media-amazon.com/images/M/MV5BZmNjZWI3NzktYWI1Mi00OTAyLWJkNTYtMzUwYTFlZDA0Y2UwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1013_.jpg",
        rating: 5,
    }
];